export enum LocationType {
  ROOT = "ROOT",
  AREA = "AREA",
  POINT = "POINT",
}

export enum QuizDispatchType {
  ADD_SUBLOCATION = "ADD_SUBLOCATION",
  SET_SUBLOCATION_IDS = "SET_SUBLOCATION_IDS",
  RENAME_LOCATION = "RENAME_LOCATION",
  SET_BUILDER_SELECTED = "SET_BUILDER_SELECTED",
  RESET_TAKER_SELECTED = "RESET_TAKER_SELECTED",
  MARK_TAKER_SELECTED = "MARK_TAKER_SELECTED",
  SET_AREA_IS_OPEN = "SET_AREA_IS_OPEN",
  SET_AREA_IS_ADDING = "SET_AREA_IS_ADDING",
  DELETE_LOCATION = "DELETE_LOCATION",
}

export enum SearchStatus {
  SEARCHING = "SEARCHING",
  SEARCHED = "SEARCHED",
}
