export enum FeatureType {
  ROOT = "ROOT",
  AREA = "AREA",
  POINT = "POINT",
}

export enum AllFeaturesDispatchType {
  ADD_SUBFEATURE = "ADD_SUBFEATURE",
  SET_SUBFEATURES = "SET_SUBFEATURE_IDS",
  RENAME_FEATURE = "RENAME_FEATURE",
  SET_SELECTED = "SET_BUILDER_SELECTED",
  RESET_TAKER = "RESET_TAKER_SELECTED",
  MARK_TAKER_SELECTED = "MARK_TAKER_SELECTED",
  SELECT_OPTION = "SELECT_OPTION",
  DELETE_FEATURE = "DELETE_FEATURE",
}

export enum QuizBuilderStateDispatchType {
  SET_ACTIVE_SEARCH_OPTION = "SET_ACTIVE_OPTION",
  SET_SELECTED_FEATURE = "SET_SELECTED_FEATURE",
  SET_AREA_IS_OPEN = "SET_AREA_IS_OPEN",
  SET_AREA_IS_ADDING = "SET_AREA_IS_ADDING",
}

export enum QuizTakerStateDispatchType {
  RESET = "RESET",
  MARK_CORRECT = "MARK_CORRECT",
  MARK_INCORRECT = "MARK_INCORRECT",
}

export enum SearchStatus {
  SEARCHING = "SEARCHING",
  SEARCHED = "SEARCHED",
}

export enum DisplayMode {
  QUIZ_BUILDER = "QUIZ_BUILDER",
  QUIZ_TAKER = "QUIZ_TAKER",
}
