import "@/styles/globals.css";
import { Metadata } from "next";
import { Nunito } from "next/font/google";
import NavBar from "@/components/NavBar";

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

const font = Nunito({ weight: ["400"], subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${font.className} min-h-screen`}>
        <NavBar />
        <main>{children}</main>
      </body>
    </html>
  );
}
